default: &default
    class: 'LoFTR'
    ckpt: '/home/ubuntu/Documents/1-pixel/1-jinxia/image-matching-toolbox/pretrained/loftr/outdoor_ds.ckpt'
    match_threshold: 0.2
    imsize: -1
    no_match_upscale: False
example:
    <<: *default
    match_threshold: 0.5
    imsize: -1
airloc:
    <<: *default
    match_threshold: 0.2
    imsize: 1024
    ransac_thres: [12]
hpatch:        
    <<: *default
    imsize: 480
    no_match_upscale: True
inloc:
    <<: *default
    match_threshold: 0.5
    npts: 4096
    imsize: 1024
    pairs: 'pairs-query-netvlad40-temporal.txt'
    rthres: 48
    skip_matches: 20

aachen:
    <<: *default
    match_threshold: 0.5 # Save all matches
    pairs: ['pairs-db-covis20.txt', 'pairs-query-netvlad50.txt']
    npts: 4096
    imsize: 1024
    qt_dthres: 4
    qt_psize: 48
    qt_unique: True
    ransac_thres: [20]
    sc_thres: 0.2 # Filtering during quantization
    covis_cluster: True